"""HTML report generation for checkpoint captures."""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any, Literal

from roboharness.evaluate.result import EvaluationResult, Severity, Verdict

MeshcatMode = Literal["iframe", "link", "none"]

_VERDICT_CSS = {
    Verdict.PASS: "verdict-pass",
    Verdict.DEGRADED: "verdict-degraded",
    Verdict.FAIL: "verdict-fail",
}

_VERDICT_LABEL = {
    Verdict.PASS: "PASS",
    Verdict.DEGRADED: "DEGRADED",
    Verdict.FAIL: "FAIL",
}


def _build_verdict_banner(result: EvaluationResult) -> str:
    """Build the HTML verdict banner shown at the top of the report."""
    css_class = _VERDICT_CSS[result.verdict]
    label = _VERDICT_LABEL[result.verdict]
    passed_count = len(result.passed)
    total = len(result.results)
    return (
        f'<div class="verdict {css_class}">'
        f"{label} &mdash; {passed_count}/{total} constraints satisfied"
        f"</div>"
    )


def _build_eval_summary(result: EvaluationResult) -> str:
    """Build the constraint evaluation summary table."""
    rows: list[str] = []
    for r in result.results:
        if r.passed:
            icon = '<span class="badge badge-pass">PASS</span>'
        else:
            icon = '<span class="badge badge-fail">FAIL</span>'

        if isinstance(r.threshold, tuple):
            expected = f"in [{r.threshold[0]}, {r.threshold[1]}]"
        else:
            expected = f"{r.operator.value} {r.threshold}"

        actual = f"{r.actual_value}" if r.actual_value is not None else "missing"
        severity_cls = f"severity-{r.severity.value}"
        rows.append(
            f"<tr>"
            f"<td>{r.metric}</td>"
            f"<td>{expected}</td>"
            f"<td>{actual}</td>"
            f'<td><span class="severity {severity_cls}">{r.severity.value}</span></td>'
            f"<td>{icon}</td>"
            f"</tr>"
        )

    return (
        '<div class="eval-summary">'
        "<h3>Constraint Evaluation</h3>"
        '<div class="table-scroll"><table class="eval-table">'
        "<tr><th>Metric</th><th>Expected</th><th>Actual</th>"
        "<th>Severity</th><th>Result</th></tr>" + "".join(rows) + "</table></div></div>"
    )


def _phase_badge(result: EvaluationResult, checkpoint_name: str) -> str:
    """Build a pass/fail badge for a checkpoint if phase-specific assertions exist."""
    phase_results = [r for r in result.results if r.phase == checkpoint_name]
    if not phase_results:
        return ""
    all_passed = all(r.passed for r in phase_results)
    if all_passed:
        return ' <span class="badge badge-pass">PASS</span>'
    has_critical = any(not r.passed and r.severity == Severity.CRITICAL for r in phase_results)
    if has_critical:
        return ' <span class="badge badge-fail">FAIL</span>'
    return ' <span class="badge badge-degraded">DEGRADED</span>'


def _checkpoint_sort_key(cp_path: Path) -> tuple[int, str]:
    """Sort checkpoints by step number (from metadata.json), falling back to name."""
    meta_file = cp_path / "metadata.json"
    if meta_file.exists():
        with meta_file.open() as fh:
            meta = json.load(fh)
        return (meta.get("step", 0), cp_path.name)
    return (0, cp_path.name)


def generate_html_report(
    output_dir: Path,
    task_name: str,
    *,
    title: str = "Roboharness Report",
    subtitle: str = "",
    accent_color: str = "#4a90d9",
    summary_html: str = "",
    footer_text: str = "",
    trial_name: str = "trial_001",
    meshcat_mode: MeshcatMode = "iframe",
    evaluation_result: EvaluationResult | None = None,
) -> Path:
    """Generate a self-contained HTML report showing all checkpoint captures.

    Images are embedded as base64 so the HTML file works standalone.

    Parameters
    ----------
    output_dir:
        Root output directory containing task_name/trial_name/ subdirectories.
    task_name:
        Name of the task (subdirectory under output_dir).
    title:
        HTML page title and h1 heading.
    subtitle:
        Optional paragraph below the title.
    accent_color:
        CSS color for headings and accents.
    summary_html:
        Optional HTML block inserted before checkpoints (e.g., model info).
    footer_text:
        Text for the footer. Defaults to "Generated by roboharness".
    trial_name:
        Trial subdirectory name.
    meshcat_mode:
        How to embed Meshcat scenes: "iframe" (embedded), "link" (new tab), or "none".
    evaluation_result:
        Optional constraint evaluation result. When provided, the report includes
        a verdict banner (green/yellow/red), a constraint summary table, and
        per-checkpoint pass/fail badges for phase-specific assertions.

    Returns
    -------
    Path
        Path to the generated HTML file.
    """
    trial_dir = output_dir / task_name / trial_name
    report_path = output_dir / f"{task_name}_report.html"

    if not trial_dir.exists():
        raise FileNotFoundError(f"trial directory not found: {trial_dir}")

    checkpoints = sorted(
        [d for d in trial_dir.iterdir() if d.is_dir()],
        key=_checkpoint_sort_key,
    )

    rows_html = []
    for cp_dir in checkpoints:
        cp_name = cp_dir.name

        # Read metadata
        meta_path = cp_dir / "metadata.json"
        meta: dict[str, Any] = {}
        if meta_path.exists():
            with meta_path.open() as f:
                meta = json.load(f)

        # Collect images
        images_html = []
        for img_file in sorted(cp_dir.glob("*_rgb.png")):
            cam_name = img_file.stem.replace("_rgb", "")
            with img_file.open("rb") as f:
                b64 = base64.b64encode(f.read()).decode()
            images_html.append(
                f'<div class="cam">'
                f'<img src="data:image/png;base64,{b64}" alt="{cam_name}"/>'
                f"<p>{cam_name}</p></div>"
            )

        # Meshcat interactive viewer
        meshcat_html = ""
        if meshcat_mode != "none":
            meshcat_file = cp_dir / "meshcat_scene.html"
            if meshcat_file.exists():
                meshcat_rel = meshcat_file.relative_to(output_dir).as_posix()
                iframe_title = f"{cp_name} interactive 3D scene"
                if meshcat_mode == "iframe":
                    meshcat_html = (
                        f'<div class="meshcat-viewer">'
                        f"<h3>Interactive 3D Scene</h3>"
                        f'<iframe src="{meshcat_rel}" loading="lazy" title="{iframe_title}"></iframe>'
                        f"<p>Rotate, pan, and zoom to explore the scene.</p>"
                        f"</div>"
                    )
                else:  # "link"
                    size_mb = meshcat_file.stat().st_size / (1024 * 1024)
                    meshcat_html = (
                        f'<div class="meshcat-viewer">'
                        f"<h3>Interactive 3D Scene</h3>"
                        f'<a href="{meshcat_rel}" target="_blank" class="meshcat-link">'
                        f"Open in new tab</a>"
                        f"<p>Self-contained Three.js viewer ({size_mb:.1f} MB). "
                        f"Rotate, pan, and zoom to explore.</p>"
                        f"</div>"
                    )

        # Build metadata line
        meta_parts = []
        step = meta.get("step", "?")
        meta_parts.append(f"Step: {step}")
        sim_time = meta.get("sim_time")
        if sim_time is not None:
            sim_time_str = f"{sim_time:.3f}" if isinstance(sim_time, float) else str(sim_time)
            meta_parts.append(f"Sim time: {sim_time_str}s")
        cameras = meta.get("cameras")
        if cameras:
            meta_parts.append(f"Cameras: {', '.join(cameras)}")
        capability = meta.get("camera_capability")
        if capability and capability != "none":
            meta_parts.append(f"Capability: {capability}")

        has_meshcat = bool(meshcat_html)
        views_wrap = (
            f'<div class="checkpoint-content">'
            f'<div class="views">{"".join(images_html)}</div>'
            f"{meshcat_html}</div>"
            if has_meshcat
            else f'<div class="views">{"".join(images_html)}</div>'
        )

        checkpoint_badge = _phase_badge(evaluation_result, cp_name) if evaluation_result else ""

        rows_html.append(
            f'<div class="checkpoint">'
            f"<h2>{cp_name}{checkpoint_badge}</h2>"
            f"<p>{' | '.join(meta_parts)}</p>"
            f"{views_wrap}"
            f"</div>"
        )

    if not footer_text:
        footer_text = "Generated by <code>roboharness</code>"

    subtitle_html = f"<p>{subtitle}</p>" if subtitle else ""
    summary_block = f'<div class="summary">{summary_html}</div>' if summary_html else ""

    verdict_banner = _build_verdict_banner(evaluation_result) if evaluation_result else ""
    eval_summary = _build_eval_summary(evaluation_result) if evaluation_result else ""

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  html {{ box-sizing: border-box; }}
  *, *::before, *::after {{ box-sizing: inherit; }}
  body {{ font-family: -apple-system, sans-serif; max-width: 1400px; margin: 0 auto; padding: 20px;
         background: #f5f5f5; }}
  h1 {{ color: #333; border-bottom: 2px solid {accent_color}; padding-bottom: 10px; }}
  .summary {{ background: #e8f4fd; border-radius: 8px; padding: 16px; margin: 20px 0; }}
  .report-grid {{ display: grid; gap: 16px;
                  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); }}
  .summary-card {{ background: white; border-radius: 8px; padding: 16px;
                   box-shadow: 0 1px 2px rgba(0,0,0,0.08); }}
  .summary-card h3 {{ margin-top: 0; color: {accent_color}; }}
  .alarm-grid {{ display: grid; gap: 12px;
                 grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
                 margin: 20px 0; }}
  .alarm-card {{ background: white; border-left: 4px solid #dc3545; border-radius: 8px;
                 padding: 14px 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.08); }}
  .alarm-card.ok {{ border-left-color: #2f855a; }}
  .alarm-card small {{ display: block; color: #666; text-transform: uppercase;
                       letter-spacing: 0.04em; font-size: 11px; }}
  .alarm-card strong {{ display: block; margin: 6px 0; color: #222; }}
  .alarm-card p {{ margin: 4px 0 0; font-size: 14px; color: #555; }}
  .agent-panel {{ background: linear-gradient(135deg, {accent_color}, #16324f); color: white;
                  border-radius: 10px; padding: 18px 20px; margin: 20px 0; }}
  .agent-panel strong {{ display: block; font-size: 16px; }}
  .agent-panel p {{ margin: 8px 0 0; line-height: 1.5; }}
  .phase-timeline {{ display: grid; gap: 12px;
                     grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }}
  .phase-card {{ border: 1px solid #d6d6d6; border-radius: 8px; padding: 12px;
                 background: #fafafa; }}
  .phase-card h4 {{ margin: 0 0 8px; color: #1f2937; }}
  .phase-card p {{ margin: 4px 0 0; font-size: 14px; color: #555; }}
  .phase-card-ok {{ border-color: #c6f6d5; background: #f0fff4; }}
  .phase-card-degraded {{ border-color: #f6e05e; background: #fffbea; }}
  .phase-card-fail {{ border-color: #feb2b2; background: #fff5f5; }}
  .table-scroll {{ width: 100%; overflow-x: auto; -webkit-overflow-scrolling: touch; }}
  .meta-table {{ width: 100%; border-collapse: collapse; }}
  .meta-table th, .meta-table td {{ padding: 8px 10px; text-align: left;
                                    border-bottom: 1px solid #eee; }}
  .meta-table th {{ width: 34%; color: #4b5563; font-weight: 600; }}
  .meta-table td code {{ white-space: normal; overflow-wrap: anywhere; word-break: break-word; }}
  .checkpoint {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
                 box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .checkpoint h2 {{ color: {accent_color}; margin-top: 0; }}
  .checkpoint-content {{ display: flex; gap: 24px; flex-wrap: wrap; align-items: flex-start; }}
  .views {{ display: flex; gap: 16px; flex-wrap: wrap; flex: 1; min-width: 0; }}
  .cam {{ text-align: center; }}
  .cam img {{ max-width: 320px; border: 1px solid #ddd; border-radius: 4px; }}
  .cam p {{ margin: 4px 0 0; font-size: 14px; color: #666; }}
  .meshcat-viewer {{ flex: 1 1 480px; max-width: 100%; text-align: center; }}
  .meshcat-viewer h3 {{ color: {accent_color}; margin: 0 0 8px; font-size: 16px; }}
  .meshcat-viewer iframe {{ width: 100%; max-width: 480px; height: 400px; border: 1px solid #ddd;
                            border-radius: 4px; display: block; margin: 0 auto; }}
  .meshcat-link {{ display: inline-block; padding: 10px 20px; background: {accent_color};
                   color: white; text-decoration: none; border-radius: 4px; font-weight: bold; }}
  .meshcat-link:hover {{ opacity: 0.85; }}
  .meshcat-viewer p {{ margin: 8px 0 0; font-size: 13px; color: #888; }}
  .footer {{ margin-top: 30px; color: #999; font-size: 12px; }}
  .verdict {{ padding: 12px 20px; border-radius: 8px; font-weight: bold; font-size: 18px;
              margin: 20px 0; text-align: center; }}
  .verdict-pass {{ background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }}
  .verdict-degraded {{ background: #fff3cd; color: #856404; border: 1px solid #ffeeba; }}
  .verdict-fail {{ background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }}
  .eval-summary {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
                   box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .eval-summary h3 {{ color: {accent_color}; margin-top: 0; }}
  .eval-table {{ width: 100%; min-width: 640px; border-collapse: collapse; }}
  .eval-table th, .eval-table td {{ padding: 8px 12px; text-align: left;
                                    border-bottom: 1px solid #eee; }}
  .eval-table th {{ background: #f8f9fa; font-weight: 600; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px;
            font-size: 12px; font-weight: bold; text-transform: uppercase; }}
  .badge-pass {{ background: #d4edda; color: #155724; }}
  .badge-degraded {{ background: #fff3cd; color: #856404; }}
  .badge-fail {{ background: #f8d7da; color: #721c24; }}
  .severity {{ display: inline-block; padding: 1px 6px; border-radius: 3px;
               font-size: 11px; text-transform: uppercase; }}
  .severity-critical {{ background: #f8d7da; color: #721c24; }}
  .severity-major {{ background: #fff3cd; color: #856404; }}
  .severity-minor {{ background: #e2e3e5; color: #383d41; }}
  .severity-info {{ background: #d1ecf1; color: #0c5460; }}
  .evidence-section {{ background: white; border-radius: 10px; padding: 20px; margin: 20px 0;
                     box-shadow: 0 2px 4px rgba(0,0,0,0.08); }}
  .evidence-section-head {{ display: flex; justify-content: space-between; gap: 16px;
                           align-items: flex-start; flex-wrap: wrap; margin-bottom: 16px; }}
  .evidence-section-head h3 {{ color: {accent_color}; margin: 0; }}
  .evidence-section-head p {{ margin: 6px 0 0; color: #4b5563; }}
  .evidence-state-label {{ margin: 0; font-weight: 700; color: #0f172a; }}
  .evidence-banner {{ border-radius: 8px; padding: 12px 14px; margin-bottom: 14px;
                     border: 1px solid #dbeafe; background: #eff6ff; color: #1e3a8a; }}
  .evidence-banner p {{ margin: 0; line-height: 1.5; }}
  .evidence-banner-pass {{ background: #ecfdf3; border-color: #bbf7d0; color: #166534; }}
  .evidence-banner-partial, .evidence-banner-ambiguous {{
    background: #fffbea;
    border-color: #fde68a;
    color: #92400e;
  }}
  .evidence-banner-empty, .evidence-banner-mismatch {{
    background: #fff5f5;
    border-color: #fecaca;
    color: #991b1b;
  }}
  .evidence-grid {{
    display: grid;
    gap: 16px;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  }}
  .evidence-card {{
    border: 1px solid #d6d6d6;
    border-radius: 10px;
    padding: 16px;
    background: #fafafa;
  }}
  .evidence-card-full {{ border-color: #bfdbfe; background: #f8fbff; }}
  .evidence-card-partial, .evidence-card-ambiguous {{ border-color: #fde68a; background: #fffdf5; }}
  .evidence-card-empty {{ border-color: #fecaca; background: #fff8f8; }}
  .evidence-card-head {{ display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }}
  .evidence-badge {{ display: inline-flex; align-items: center; min-height: 28px; padding: 0 10px;
                    border-radius: 999px; background: #e5eefc; color: #1e3a8a; font-size: 12px;
                    font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em; }}
  .evidence-badge-status {{ background: #e5e7eb; color: #111827; }}
  .evidence-compare-grid {{
    display: grid;
    gap: 12px;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }}
  .evidence-figure {{ margin: 0; }}
  .evidence-role {{
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #4b5563;
    margin-bottom: 8px;
  }}
  .evidence-figure img {{ width: 100%; aspect-ratio: 4 / 3; object-fit: cover; border-radius: 8px;
                         border: 1px solid #d1d5db; background: #e5e7eb; }}
  .evidence-figure figcaption {{
    margin-top: 8px;
    font-size: 13px;
    color: #4b5563;
    line-height: 1.4;
  }}
  .evidence-placeholder {{ width: 100%; aspect-ratio: 4 / 3; display: flex; align-items: center;
                          justify-content: center; border: 1px dashed #f59e0b; border-radius: 8px;
                          background: #fffbeb; color: #92400e; font-weight: 700; }}
  .evidence-chip-row {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }}
  .metric-chip {{ display: inline-flex; align-items: center; min-height: 28px; padding: 4px 10px;
                 border-radius: 999px; background: #e2e8f0; color: #0f172a; font-size: 12px;
                 line-height: 1.4; }}
  .evidence-caption, .evidence-diagnostic {{ margin: 12px 0 0; line-height: 1.5; }}
  .evidence-diagnostic {{ color: #92400e; }}
  @media (max-width: 860px) {{
    .evidence-compare-grid {{ grid-template-columns: 1fr; }}
    .meshcat-viewer {{ flex-basis: 100%; }}
    .meshcat-viewer iframe {{ height: min(70vw, 400px); }}
  }}
</style>
</head>
<body>
<h1>{title}</h1>
{subtitle_html}
{verdict_banner}
{summary_block}
{eval_summary}
{"".join(rows_html)}
<div class="footer">
  {footer_text}
</div>
</body>
</html>
"""
    report_path.write_text(html)
    return report_path
