"""HTML report generation for checkpoint captures."""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any


def generate_html_report(
    output_dir: Path,
    task_name: str,
    *,
    title: str = "Roboharness Report",
    subtitle: str = "",
    accent_color: str = "#4a90d9",
    summary_html: str = "",
    footer_text: str = "",
    trial_name: str = "trial_001",
    meshcat_mode: str = "iframe",  # "iframe", "link", or "none"
) -> Path:
    """Generate a self-contained HTML report showing all checkpoint captures.

    Images are embedded as base64 so the HTML file works standalone.

    Parameters
    ----------
    output_dir:
        Root output directory containing task_name/trial_name/ subdirectories.
    task_name:
        Name of the task (subdirectory under output_dir).
    title:
        HTML page title and h1 heading.
    subtitle:
        Optional paragraph below the title.
    accent_color:
        CSS color for headings and accents.
    summary_html:
        Optional HTML block inserted before checkpoints (e.g., model info).
    footer_text:
        Text for the footer. Defaults to "Generated by roboharness".
    trial_name:
        Trial subdirectory name.
    meshcat_mode:
        How to embed Meshcat scenes: "iframe" (embedded), "link" (new tab), or "none".

    Returns
    -------
    Path
        Path to the generated HTML file.
    """
    trial_dir = output_dir / task_name / trial_name
    report_path = output_dir / f"{task_name}_report.html"

    if not trial_dir.exists():
        return report_path

    checkpoints = sorted(
        [d for d in trial_dir.iterdir() if d.is_dir()],
        key=lambda p: p.name,
    )

    rows_html = []
    for cp_dir in checkpoints:
        cp_name = cp_dir.name

        # Read metadata
        meta_path = cp_dir / "metadata.json"
        meta: dict[str, Any] = {}
        if meta_path.exists():
            with meta_path.open() as f:
                meta = json.load(f)

        # Collect images
        images_html = []
        for img_file in sorted(cp_dir.glob("*_rgb.png")):
            cam_name = img_file.stem.replace("_rgb", "")
            with img_file.open("rb") as f:
                b64 = base64.b64encode(f.read()).decode()
            images_html.append(
                f'<div class="cam">'
                f'<img src="data:image/png;base64,{b64}" alt="{cam_name}"/>'
                f"<p>{cam_name}</p></div>"
            )

        # Meshcat interactive viewer
        meshcat_html = ""
        if meshcat_mode != "none":
            meshcat_file = cp_dir / "meshcat_scene.html"
            if meshcat_file.exists():
                meshcat_rel = f"{cp_name}/meshcat_scene.html"
                if meshcat_mode == "iframe":
                    meshcat_html = (
                        f'<div class="meshcat-viewer">'
                        f"<h3>Interactive 3D Scene</h3>"
                        f'<iframe src="{meshcat_rel}" loading="lazy"></iframe>'
                        f"<p>Rotate, pan, and zoom to explore the scene.</p>"
                        f"</div>"
                    )
                else:  # "link"
                    size_mb = meshcat_file.stat().st_size / (1024 * 1024)
                    meshcat_html = (
                        f'<div class="meshcat-viewer">'
                        f"<h3>Interactive 3D Scene</h3>"
                        f'<a href="{meshcat_rel}" target="_blank" class="meshcat-link">'
                        f"Open in new tab</a>"
                        f"<p>Self-contained Three.js viewer ({size_mb:.1f} MB). "
                        f"Rotate, pan, and zoom to explore.</p>"
                        f"</div>"
                    )

        # Build metadata line
        meta_parts = []
        step = meta.get("step", "?")
        meta_parts.append(f"Step: {step}")
        sim_time = meta.get("sim_time")
        if sim_time is not None:
            if isinstance(sim_time, float):
                sim_time = f"{sim_time:.3f}"
            meta_parts.append(f"Sim time: {sim_time}s")
        cameras = meta.get("cameras")
        if cameras:
            meta_parts.append(f"Cameras: {', '.join(cameras)}")
        capability = meta.get("camera_capability")
        if capability and capability != "none":
            meta_parts.append(f"Capability: {capability}")

        has_meshcat = bool(meshcat_html)
        views_wrap = (
            f'<div class="checkpoint-content">'
            f'<div class="views">{"".join(images_html)}</div>'
            f"{meshcat_html}</div>"
            if has_meshcat
            else f'<div class="views">{"".join(images_html)}</div>'
        )

        rows_html.append(
            f'<div class="checkpoint">'
            f"<h2>{cp_name}</h2>"
            f"<p>{' | '.join(meta_parts)}</p>"
            f"{views_wrap}"
            f"</div>"
        )

    if not footer_text:
        footer_text = "Generated by <code>roboharness</code>"

    subtitle_html = f"<p>{subtitle}</p>" if subtitle else ""
    summary_block = f'<div class="summary">{summary_html}</div>' if summary_html else ""

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 1400px; margin: 0 auto; padding: 20px;
         background: #f5f5f5; }}
  h1 {{ color: #333; border-bottom: 2px solid {accent_color}; padding-bottom: 10px; }}
  .summary {{ background: #e8f4fd; border-radius: 8px; padding: 16px; margin: 20px 0; }}
  .checkpoint {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
                 box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .checkpoint h2 {{ color: {accent_color}; margin-top: 0; }}
  .checkpoint-content {{ display: flex; gap: 24px; flex-wrap: wrap; align-items: flex-start; }}
  .views {{ display: flex; gap: 16px; flex-wrap: wrap; flex: 1; min-width: 300px; }}
  .cam {{ text-align: center; }}
  .cam img {{ max-width: 320px; border: 1px solid #ddd; border-radius: 4px; }}
  .cam p {{ margin: 4px 0 0; font-size: 14px; color: #666; }}
  .meshcat-viewer {{ flex: 0 0 480px; text-align: center; }}
  .meshcat-viewer h3 {{ color: {accent_color}; margin: 0 0 8px; font-size: 16px; }}
  .meshcat-viewer iframe {{ width: 480px; height: 400px; border: 1px solid #ddd;
                            border-radius: 4px; }}
  .meshcat-link {{ display: inline-block; padding: 10px 20px; background: {accent_color};
                   color: white; text-decoration: none; border-radius: 4px; font-weight: bold; }}
  .meshcat-link:hover {{ opacity: 0.85; }}
  .meshcat-viewer p {{ margin: 8px 0 0; font-size: 13px; color: #888; }}
  .footer {{ margin-top: 30px; color: #999; font-size: 12px; }}
</style>
</head>
<body>
<h1>{title}</h1>
{subtitle_html}
{summary_block}
{"".join(rows_html)}
<div class="footer">
  {footer_text}
</div>
</body>
</html>
"""
    report_path.write_text(html)
    return report_path
