"""Tests for HTML report generation."""

from __future__ import annotations

import json
from pathlib import Path

from roboharness.reporting import generate_html_report


def _create_checkpoint(
    trial_dir: Path,
    name: str,
    *,
    step: int = 0,
    sim_time: float | None = None,
    cameras: list[str] | None = None,
    capability: str | None = None,
    images: list[str] | None = None,
) -> Path:
    """Helper to create a checkpoint directory with metadata and dummy images."""
    cp_dir = trial_dir / name
    cp_dir.mkdir(parents=True, exist_ok=True)

    meta: dict = {"step": step}
    if sim_time is not None:
        meta["sim_time"] = sim_time
    if cameras is not None:
        meta["cameras"] = cameras
    if capability is not None:
        meta["camera_capability"] = capability
    (cp_dir / "metadata.json").write_text(json.dumps(meta))

    for img_name in images or ["front"]:
        # 1x1 red PNG (minimal valid PNG)
        _write_tiny_png(cp_dir / f"{img_name}_rgb.png")

    return cp_dir


def _write_tiny_png(path: Path) -> None:
    """Write a minimal 1x1 red PNG file."""
    import base64

    # Minimal valid 1x1 red PNG
    b = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4"
        "nGP4z8BQDwAEgAF/pooBPQAAAABJRU5ErkJggg=="
    )
    path.write_bytes(b)


def test_generate_report_empty_trial_dir(tmp_path):
    """Report returns path even when trial dir doesn't exist."""
    report_path = generate_html_report(tmp_path, "my_task")
    assert report_path == tmp_path / "my_task_report.html"
    # File is not written when trial_dir is missing
    assert not report_path.exists()


def test_generate_report_with_checkpoints(tmp_path):
    """Report is generated with checkpoint images embedded as base64."""
    trial_dir = tmp_path / "my_task" / "trial_001"
    trial_dir.mkdir(parents=True)

    _create_checkpoint(trial_dir, "01_start", step=0, sim_time=0.0, cameras=["front"])
    _create_checkpoint(trial_dir, "02_grasp", step=100, sim_time=1.5)

    report_path = generate_html_report(tmp_path, "my_task", title="Test Report")

    assert report_path.exists()
    html = report_path.read_text()
    assert "Test Report" in html
    assert "01_start" in html
    assert "02_grasp" in html
    assert "data:image/png;base64," in html
    assert "Step: 0" in html
    assert "Step: 100" in html
    assert "Sim time: 0.000s" in html
    assert "Sim time: 1.500s" in html
    assert "Cameras: front" in html


def test_generate_report_subtitle_and_summary(tmp_path):
    """Report includes subtitle and summary HTML."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(
        tmp_path,
        "task",
        subtitle="My subtitle",
        summary_html="<p>Summary info</p>",
    )
    html = report_path.read_text()
    assert "<p>My subtitle</p>" in html
    assert "<p>Summary info</p>" in html


def test_generate_report_custom_footer(tmp_path):
    """Custom footer text is rendered."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task", footer_text="Custom footer")
    html = report_path.read_text()
    assert "Custom footer" in html


def test_generate_report_default_footer(tmp_path):
    """Default footer is 'Generated by roboharness'."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Generated by <code>roboharness</code>" in html


def test_generate_report_no_metadata(tmp_path):
    """Checkpoint without metadata.json still renders."""
    trial_dir = tmp_path / "task" / "trial_001"
    cp_dir = trial_dir / "cp1"
    cp_dir.mkdir(parents=True)
    _write_tiny_png(cp_dir / "front_rgb.png")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "cp1" in html
    assert "Step: ?" in html


def test_generate_report_camera_capability(tmp_path):
    """Capability field is shown when not 'none'."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, capability="multi_angle")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Capability: multi_angle" in html


def test_generate_report_capability_none_hidden(tmp_path):
    """Capability 'none' is not shown."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, capability="none")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Capability:" not in html


def test_generate_report_meshcat_iframe(tmp_path):
    """Meshcat scene in iframe mode embeds an iframe."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="iframe")
    html = report_path.read_text()
    assert "<iframe" in html
    assert "meshcat_scene.html" in html


def test_generate_report_meshcat_link(tmp_path):
    """Meshcat scene in link mode shows open-in-new-tab link."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="link")
    html = report_path.read_text()
    assert "Open in new tab" in html
    assert 'target="_blank"' in html


def test_generate_report_meshcat_none(tmp_path):
    """Meshcat mode 'none' skips meshcat embedding."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="none")
    html = report_path.read_text()
    assert "<iframe" not in html
    assert "Open in new tab" not in html


def test_generate_report_multiple_cameras(tmp_path):
    """Multiple camera images are all embedded."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, images=["front", "side", "top"])

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "front" in html
    assert "side" in html
    assert "top" in html


def test_generate_report_accent_color(tmp_path):
    """Custom accent color appears in CSS."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task", accent_color="#ff0000")
    html = report_path.read_text()
    assert "#ff0000" in html
