"""Tests for HTML report generation."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from roboharness.evaluate.assertions import AssertionEngine, MetricAssertion
from roboharness.evaluate.result import EvaluationResult, Operator, Severity
from roboharness.reporting import generate_html_report


def _create_checkpoint(
    trial_dir: Path,
    name: str,
    *,
    step: int = 0,
    sim_time: float | None = None,
    cameras: list[str] | None = None,
    capability: str | None = None,
    images: list[str] | None = None,
) -> Path:
    """Helper to create a checkpoint directory with metadata and dummy images."""
    cp_dir = trial_dir / name
    cp_dir.mkdir(parents=True, exist_ok=True)

    meta: dict = {"step": step}
    if sim_time is not None:
        meta["sim_time"] = sim_time
    if cameras is not None:
        meta["cameras"] = cameras
    if capability is not None:
        meta["camera_capability"] = capability
    (cp_dir / "metadata.json").write_text(json.dumps(meta))

    for img_name in images or ["front"]:
        # 1x1 red PNG (minimal valid PNG)
        _write_tiny_png(cp_dir / f"{img_name}_rgb.png")

    return cp_dir


def _write_tiny_png(path: Path) -> None:
    """Write a minimal 1x1 red PNG file."""
    import base64

    # Minimal valid 1x1 red PNG
    b = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4"
        "nGP4z8BQDwAEgAF/pooBPQAAAABJRU5ErkJggg=="
    )
    path.write_bytes(b)


def test_generate_report_empty_trial_dir(tmp_path):
    """Report raises FileNotFoundError when trial dir doesn't exist."""
    with pytest.raises(FileNotFoundError, match="trial directory not found"):
        generate_html_report(tmp_path, "my_task")


def test_generate_report_with_checkpoints(tmp_path):
    """Report is generated with checkpoint images embedded as base64."""
    trial_dir = tmp_path / "my_task" / "trial_001"
    trial_dir.mkdir(parents=True)

    _create_checkpoint(trial_dir, "01_start", step=0, sim_time=0.0, cameras=["front"])
    _create_checkpoint(trial_dir, "02_grasp", step=100, sim_time=1.5)

    report_path = generate_html_report(tmp_path, "my_task", title="Test Report")

    assert report_path.exists()
    html = report_path.read_text()
    assert "Test Report" in html
    assert "01_start" in html
    assert "02_grasp" in html
    assert "data:image/png;base64," in html
    assert "Step: 0" in html
    assert "Step: 100" in html
    assert "Sim time: 0.000s" in html
    assert "Sim time: 1.500s" in html
    assert "Cameras: front" in html


def test_generate_report_subtitle_and_summary(tmp_path):
    """Report includes subtitle and summary HTML."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(
        tmp_path,
        "task",
        subtitle="My subtitle",
        summary_html="<p>Summary info</p>",
    )
    html = report_path.read_text()
    assert "<p>My subtitle</p>" in html
    assert "<p>Summary info</p>" in html


def test_generate_report_custom_footer(tmp_path):
    """Custom footer text is rendered."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task", footer_text="Custom footer")
    html = report_path.read_text()
    assert "Custom footer" in html


def test_generate_report_default_footer(tmp_path):
    """Default footer is 'Generated by roboharness'."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Generated by <code>roboharness</code>" in html


def test_generate_report_no_metadata(tmp_path):
    """Checkpoint without metadata.json still renders."""
    trial_dir = tmp_path / "task" / "trial_001"
    cp_dir = trial_dir / "cp1"
    cp_dir.mkdir(parents=True)
    _write_tiny_png(cp_dir / "front_rgb.png")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "cp1" in html
    assert "Step: ?" in html


def test_generate_report_camera_capability(tmp_path):
    """Capability field is shown when not 'none'."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, capability="multi_angle")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Capability: multi_angle" in html


def test_generate_report_capability_none_hidden(tmp_path):
    """Capability 'none' is not shown."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, capability="none")

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "Capability:" not in html


def test_generate_report_meshcat_iframe(tmp_path):
    """Meshcat scene in iframe mode embeds an iframe."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="iframe")
    html = report_path.read_text()
    assert "<iframe" in html
    assert "meshcat_scene.html" in html


def test_generate_report_meshcat_link(tmp_path):
    """Meshcat scene in link mode shows open-in-new-tab link."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="link")
    html = report_path.read_text()
    assert "Open in new tab" in html
    assert 'target="_blank"' in html


def test_generate_report_meshcat_none(tmp_path):
    """Meshcat mode 'none' skips meshcat embedding."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    cp_dir = _create_checkpoint(trial_dir, "cp1", step=1)
    (cp_dir / "meshcat_scene.html").write_text("<html>meshcat</html>")

    report_path = generate_html_report(tmp_path, "task", meshcat_mode="none")
    html = report_path.read_text()
    assert "<iframe" not in html
    assert "Open in new tab" not in html


def test_generate_report_multiple_cameras(tmp_path):
    """Multiple camera images are all embedded."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1, images=["front", "side", "top"])

    report_path = generate_html_report(tmp_path, "task")
    html = report_path.read_text()
    assert "front" in html
    assert "side" in html
    assert "top" in html


def test_generate_report_accent_color(tmp_path):
    """Custom accent color appears in CSS."""
    trial_dir = tmp_path / "task" / "trial_001"
    trial_dir.mkdir(parents=True)
    _create_checkpoint(trial_dir, "cp1", step=1)

    report_path = generate_html_report(tmp_path, "task", accent_color="#ff0000")
    html = report_path.read_text()
    assert "#ff0000" in html


# ---------------------------------------------------------------------------
# Evaluation integration tests
# ---------------------------------------------------------------------------


def _make_passing_result() -> EvaluationResult:
    """Create an EvaluationResult where all assertions pass."""
    assertions = [
        MetricAssertion("grip_center_error_mm", Operator.LT, 50.0, Severity.CRITICAL),
        MetricAssertion("pinch_gap_error_mm", Operator.LT, 15.0, Severity.CRITICAL),
    ]
    report = {
        "summary_metrics": {
            "grip_center_error_mm": 5.0,
            "pinch_gap_error_mm": 8.0,
        }
    }
    return AssertionEngine(assertions).evaluate(report)


def _make_failing_result() -> EvaluationResult:
    """Create an EvaluationResult with critical failures."""
    assertions = [
        MetricAssertion("grip_center_error_mm", Operator.LT, 50.0, Severity.CRITICAL),
        MetricAssertion("pinch_gap_error_mm", Operator.LT, 15.0, Severity.CRITICAL),
    ]
    report = {
        "summary_metrics": {
            "grip_center_error_mm": 60.0,
            "pinch_gap_error_mm": 20.0,
        }
    }
    return AssertionEngine(assertions).evaluate(report)


def _make_degraded_result() -> EvaluationResult:
    """Create an EvaluationResult with major (not critical) failures."""
    assertions = [
        MetricAssertion("grip_center_error_mm", Operator.LT, 50.0, Severity.CRITICAL),
        MetricAssertion("pinch_elevation_deg", Operator.LT, 15.0, Severity.MAJOR),
    ]
    report = {
        "summary_metrics": {
            "grip_center_error_mm": 5.0,
            "pinch_elevation_deg": 20.0,
        }
    }
    return AssertionEngine(assertions).evaluate(report)


def _make_phase_result() -> EvaluationResult:
    """Create an EvaluationResult with phase-specific assertions."""
    assertions = [
        MetricAssertion("grip_center_error_mm", Operator.LT, 50.0, Severity.CRITICAL),
        MetricAssertion(
            "grip_center_error_mm", Operator.LT, 10.0, Severity.CRITICAL, phase="02_grasp"
        ),
    ]
    report = {
        "summary_metrics": {"grip_center_error_mm": 5.0},
        "snapshot_metrics": {"02_grasp": {"grip_center_error_mm": 9.0}},
    }
    return AssertionEngine(assertions).evaluate(report)


class TestReportWithEvaluation:
    def test_no_evaluation_unchanged(self, tmp_path):
        """Report without evaluation_result produces no verdict elements."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        report_path = generate_html_report(tmp_path, "task")
        html = report_path.read_text()
        assert "verdict" not in html.split("<style>")[0]  # not in body
        assert "Constraint Evaluation" not in html

    def test_pass_verdict_banner(self, tmp_path):
        """Passing evaluation shows green PASS banner."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        result = _make_passing_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "verdict-pass" in html
        assert "PASS" in html
        assert "2/2 constraints satisfied" in html

    def test_fail_verdict_banner(self, tmp_path):
        """Failing evaluation shows red FAIL banner."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        result = _make_failing_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "verdict-fail" in html
        assert "FAIL" in html
        assert "0/2 constraints satisfied" in html

    def test_degraded_verdict_banner(self, tmp_path):
        """Degraded evaluation shows yellow DEGRADED banner."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        result = _make_degraded_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "verdict-degraded" in html
        assert "DEGRADED" in html
        assert "1/2 constraints satisfied" in html

    def test_eval_summary_table(self, tmp_path):
        """Evaluation summary table shows metric details."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        result = _make_failing_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "Constraint Evaluation" in html
        assert "grip_center_error_mm" in html
        assert "pinch_gap_error_mm" in html
        assert "lt 50.0" in html
        assert "60.0" in html
        assert "badge-fail" in html
        assert "severity-critical" in html

    def test_eval_summary_pass_badges(self, tmp_path):
        """Passing assertions show PASS badges in summary, no FAIL badges in body."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        result = _make_passing_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        body = html.split("</style>")[1]
        assert "badge-pass" in body
        assert "badge-fail" not in body

    def test_phase_specific_badge(self, tmp_path):
        """Checkpoint with phase-specific assertions gets a badge."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "01_start", step=0)
        _create_checkpoint(trial_dir, "02_grasp", step=100)

        result = _make_phase_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        # 02_grasp should have a PASS badge (9.0 < 10.0)
        assert "02_grasp" in html
        # The phase badge should appear next to the checkpoint name
        assert 'badge badge-pass">PASS</span>' in html

    def test_phase_badge_not_on_unrelated_checkpoint(self, tmp_path):
        """Checkpoints without phase-specific assertions get no badge."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "01_start", step=0)
        _create_checkpoint(trial_dir, "02_grasp", step=100)

        result = _make_phase_result()
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        # 01_start should NOT have a badge — extract just that section
        start_idx = html.index("01_start")
        grasp_idx = html.index("02_grasp")
        start_section = html[start_idx:grasp_idx]
        assert "badge" not in start_section

    def test_phase_badge_fail(self, tmp_path):
        """Checkpoint with critical phase failure shows FAIL badge."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "02_grasp", step=100)

        assertions = [
            MetricAssertion(
                "grip_center_error_mm",
                Operator.LT,
                10.0,
                Severity.CRITICAL,
                phase="02_grasp",
            ),
        ]
        result = AssertionEngine(assertions).evaluate(
            {"snapshot_metrics": {"02_grasp": {"grip_center_error_mm": 50.0}}}
        )
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert 'badge badge-fail">FAIL</span>' in html

    def test_phase_badge_degraded(self, tmp_path):
        """Checkpoint with major (non-critical) phase failure shows DEGRADED badge."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "02_grasp", step=100)

        assertions = [
            MetricAssertion(
                "elevation_deg",
                Operator.LT,
                15.0,
                Severity.MAJOR,
                phase="02_grasp",
            ),
        ]
        result = AssertionEngine(assertions).evaluate(
            {"snapshot_metrics": {"02_grasp": {"elevation_deg": 20.0}}}
        )
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert 'badge badge-degraded">DEGRADED</span>' in html

    def test_missing_metric_shown(self, tmp_path):
        """Missing metric value is displayed as 'missing' in summary."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        assertions = [
            MetricAssertion("nonexistent_metric", Operator.LT, 10.0, Severity.CRITICAL),
        ]
        result = AssertionEngine(assertions).evaluate({"summary_metrics": {}})
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "missing" in html
        assert "nonexistent_metric" in html

    def test_in_range_assertion_display(self, tmp_path):
        """In-range assertion shows threshold range correctly."""
        trial_dir = tmp_path / "task" / "trial_001"
        trial_dir.mkdir(parents=True)
        _create_checkpoint(trial_dir, "cp1", step=1)

        assertions = [
            MetricAssertion("force", Operator.IN_RANGE, (1.0, 10.0), Severity.MAJOR),
        ]
        result = AssertionEngine(assertions).evaluate({"summary_metrics": {"force": 5.0}})
        report_path = generate_html_report(tmp_path, "task", evaluation_result=result)
        html = report_path.read_text()
        assert "in [1.0, 10.0]" in html
        assert "5.0" in html
