#!/usr/bin/env python3
"""Native LeRobot G1 Integration — controller demos on the official factory.

Uses LeRobot's ``make_env()`` to create the Unitree G1 MuJoCo environment, then
runs a selected locomotion controller via RobotHarnessWrapper to produce a visual
checkpoint report.

Supported controllers:
  - **groot**: GR00T decoupled WBC (15 lower-body joints)
  - **sonic**: SONIC kinematic planner (29 full-body joints)

Requirements:
    pip install torch --index-url https://download.pytorch.org/whl/cpu  # CPU-only
    pip install roboharness[demo] lerobot

Run:
    MUJOCO_GL=osmesa python examples/lerobot_g1_native.py --controller groot
    MUJOCO_GL=osmesa python examples/lerobot_g1_native.py --controller sonic

Output (groot):
    ./harness_output/lerobot_g1_native_groot/trial_001/
        initial/   — robot standing after reset
        walking/   — GR00T decoupled WBC walking forward
        final/     — final stopped state

Output (sonic):
    ./harness_output/lerobot_g1_native_sonic/trial_001/
        initial/   — robot standing after reset
        walking/   — SONIC planner walking forward
        final/     — final stopped state
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

from roboharness.core.protocol import TaskPhase, TaskProtocol
from roboharness.evaluate.lerobot_env import create_native_env
from roboharness.wrappers import RobotHarnessWrapper

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LEROBOT_ENV_ID = "lerobot/unitree-g1-mujoco"
DEFAULT_N_STEPS = 500

CONTROLLER_CONFIGS: dict[str, dict[str, Any]] = {
    "groot": {
        "label": "GR00T decoupled WBC",
        "accent_color": "#2d8cf0",
        "n_dof": 15,  # lower body + waist
    },
    "sonic": {
        "label": "SONIC kinematic planner",
        "accent_color": "#7c4dff",
        "n_dof": 29,  # full body
    },
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_integration(
    checkpoint_infos: list[dict[str, Any]],
    expected_count: int,
) -> list[str]:
    """Validate that the wrapper integration worked correctly."""
    failures: list[str] = []

    if len(checkpoint_infos) != expected_count:
        failures.append(f"Expected {expected_count} checkpoints, got {len(checkpoint_infos)}")

    for cp_info in checkpoint_infos:
        files = cp_info.get("files", {})
        state_path = files.get("state")
        if not state_path or not Path(state_path).exists():
            failures.append(f"Checkpoint '{cp_info['name']}': missing state.json")
            continue

        state = json.loads(Path(state_path).read_text())
        if "step" not in state or "reward" not in state:
            failures.append(f"Checkpoint '{cp_info['name']}': state.json missing required fields")

    return failures


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------


def generate_html_report(output_dir: Path, task_name: str, controller: str) -> Path:
    """Generate a self-contained HTML report with embedded checkpoint images."""
    from roboharness.reporting import generate_html_report as _generate

    cfg = CONTROLLER_CONFIGS[controller]
    return _generate(
        output_dir,
        task_name,
        title=f"LeRobot G1 Native — {cfg['label']}",
        accent_color=cfg["accent_color"],
        summary_html=(
            f"<strong>Env:</strong> <code>{LEROBOT_ENV_ID}</code> via <code>make_env()</code>"
            f"<br/><strong>Controller:</strong> {cfg['label']} ({cfg['n_dof']} DOF)"
            "<br/><strong>Integration:</strong> Native LeRobot factory + RobotHarnessWrapper"
        ),
        footer_text=(
            f"Generated by <code>examples/lerobot_g1_native.py --controller {controller}</code>"
        ),
        meshcat_mode="none",
    )


# ---------------------------------------------------------------------------
# Controller helpers
# ---------------------------------------------------------------------------


def _load_controller(name: str) -> Any:
    """Load a single locomotion controller by name. Returns None on failure."""
    try:
        if name == "groot":
            from roboharness.controllers.locomotion import GrootLocomotionController

            return GrootLocomotionController()
        elif name == "sonic":
            from roboharness.controllers.locomotion import SonicLocomotionController

            return SonicLocomotionController()
    except (ImportError, Exception) as exc:
        print(f"      Warning: could not load {name} controller ({exc})")
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Native LeRobot G1 integration — locomotion controller demo"
    )
    parser.add_argument("--output-dir", default="./harness_output", help="Output directory")
    parser.add_argument("--report", action="store_true", help="Generate HTML report")
    parser.add_argument("--n-steps", type=int, default=DEFAULT_N_STEPS, help="Number of steps")
    parser.add_argument(
        "--controller",
        choices=list(CONTROLLER_CONFIGS),
        default="groot",
        help="Locomotion controller to run (default: groot)",
    )
    parser.add_argument(
        "--assert-success", action="store_true", help="Exit non-zero on validation failure"
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    n_steps = args.n_steps
    controller_name: str = args.controller
    cfg = CONTROLLER_CONFIGS[controller_name]
    task_name = f"lerobot_g1_native_{controller_name}"

    print("=" * 60)
    print(f"  Roboharness: Native LeRobot G1 — {cfg['label']}")
    print("=" * 60)

    # 1. Create environment via make_env()
    print(f"\n[1/5] Creating environment via make_env('{LEROBOT_ENV_ID}') ...")
    env = create_native_env(LEROBOT_ENV_ID)
    print(f"      Obs space: {env.observation_space}")
    print(f"      Act space: {env.action_space}")

    # 2. Load locomotion controller
    print(f"[2/5] Loading {cfg['label']} controller ...")
    ctrl = _load_controller(controller_name)

    # Access MuJoCo data for controller state (stored by _add_mujoco_rendering)
    unwrapped = getattr(env, "unwrapped", env)
    mj_data = getattr(unwrapped, "mj_data", None)

    has_controller = ctrl is not None and mj_data is not None
    if ctrl is not None and mj_data is None:
        print("      Warning: MuJoCo data not found — falling back to random actions")
    if has_controller:
        print(f"      Loaded ({cfg['n_dof']} DOF output)")
    else:
        print("      Falling back to random actions")

    # 3. Wrap with RobotHarnessWrapper
    print("[3/5] Wrapping with RobotHarnessWrapper ...")
    episode_protocol = TaskProtocol(
        name=f"{controller_name}_locomotion",
        description=f"{cfg['label']} on native LeRobot G1",
        phases=[
            TaskPhase("initial", "Standing pose after reset"),
            TaskPhase("walking", f"{cfg['label']} walking forward"),
            TaskPhase("final", "Final stopped state"),
        ],
    )
    phase_steps = {"initial": 1, "walking": n_steps * 3 // 4, "final": n_steps}

    # Detect available cameras (added by _add_mujoco_rendering or native env)
    cameras = ["default"]
    env_cameras = getattr(unwrapped, "cameras", None) or getattr(unwrapped, "_cameras", None)
    if env_cameras:
        cameras = list(env_cameras)

    wrapped = RobotHarnessWrapper(
        env,
        protocol=episode_protocol,
        phase_steps=phase_steps,
        cameras=cameras,
        output_dir=str(output_dir),
        task_name=task_name,
        auto_fix_obs_space=True,
    )
    print(f"      Protocol: {wrapped.active_protocol.name}")
    print(f"      Multi-camera: {wrapped.has_multi_camera}")
    print(f"      Camera capability: {wrapped.camera_capability}")
    print(f"      Cameras: {cameras}")

    # 4. Run episode
    print(f"[4/5] Running episode ({n_steps} steps) ...")
    obs, _info = wrapped.reset()
    if has_controller:
        ctrl.reset()

    print(f"      Initial obs type: {type(obs).__name__}", end="")
    if hasattr(obs, "shape"):
        print(f", shape: {obs.shape}", end="")
    elif isinstance(obs, dict):
        print(f", keys: {list(obs.keys())}", end="")
    print()

    action_dim = env.action_space.shape[0] if hasattr(env.action_space, "shape") else 29
    checkpoint_infos: list[dict[str, Any]] = []

    for i in range(n_steps):
        if has_controller:
            state = {"qpos": mj_data.qpos, "qvel": mj_data.qvel}
            # Stand for first 100 steps, walk, then stop for last 50
            if i < 100:
                velocity = [0.0, 0.0, 0.0]
            elif i < n_steps - 50:
                velocity = [0.3, 0.0, 0.0]
            else:
                velocity = [0.0, 0.0, 0.0]

            targets = ctrl.compute(command={"velocity": velocity}, state=state)
            action = np.zeros(action_dim, dtype=np.float64)
            action[: len(targets)] = targets
        else:
            action = env.action_space.sample()

        obs, reward, terminated, truncated, info = wrapped.step(action)

        if "checkpoint" in info:
            cp = info["checkpoint"]
            checkpoint_infos.append(cp)
            print(f"      Checkpoint '{cp['name']}' at step {cp['step']} | reward={reward:.3f}")
            print(f"        -> {cp['capture_dir']}")

        if terminated or truncated:
            print(f"      Episode ended at step {i + 1} (terminated={terminated})")
            obs, _info = wrapped.reset()

    # 5. Validate
    print("[5/5] Validating integration ...")
    failures = validate_integration(checkpoint_infos, expected_count=len(episode_protocol.phases))

    if failures:
        print("      VALIDATION FAILED:")
        for msg in failures:
            print(f"        FAIL: {msg}")
    else:
        print("      All checks passed!")

    # Summary
    trial_dir = output_dir / task_name / "trial_001"
    total_images = len(list(trial_dir.rglob("*_rgb.png"))) if trial_dir.exists() else 0
    print(f"      {total_images} images saved to: {trial_dir}")

    if args.report:
        report_path = generate_html_report(output_dir, task_name, controller_name)
        print(f"      HTML report: {report_path}")

    print("\n  Output structure:")
    if trial_dir.exists():
        for cp_dir in sorted(trial_dir.iterdir()):
            if cp_dir.is_dir():
                files = sorted(f.name for f in cp_dir.iterdir() if f.is_file())
                print(f"    {cp_dir.name}/")
                for fname in files:
                    print(f"      {fname}")

    print("\n" + "=" * 60)
    wrapped.close()

    if args.assert_success and failures:
        print("\n  VALIDATION: FAILED")
        sys.exit(1)
    elif args.assert_success:
        print("\n  VALIDATION: PASSED")


if __name__ == "__main__":
    main()
