#!/usr/bin/env python3
"""MuJoCo grasp wedge with evaluator-backed alarms and agent-readable artifacts.

This example runs one deterministic grasp loop, emits three machine-readable
artifacts, and optionally renders an HTML report:

  1. ``autonomous_report.json`` — single source of truth for metrics and baseline comparison
  2. ``alarms.json`` — evaluator-derived alarm cards and statuses
  3. ``phase_manifest.json`` — failed phase, views to inspect, and rerun hint
  4. ``report.html`` — optional HTML report when ``--report`` is requested

Run:
    pip install roboharness[demo]
    MUJOCO_GL=osmesa python examples/mujoco_grasp.py --report --assert-success
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from roboharness.backends.mujoco_meshcat import MuJoCoMeshcatBackend
from roboharness.backends.visualizer import MeshcatVisualizer
from roboharness.core.harness import Harness
from roboharness.evaluate.result import EvaluationResult

try:
    from examples._mujoco_grasp_fixture import (
        GRASP_MJCF,
        MUJOCO_GRASP_CAMERAS,
        MUJOCO_GRASP_TASK,
        build_grasp_phases,
        build_grasp_protocol,
    )
    from examples._mujoco_grasp_wedge import (
        BASELINE_REPORT_PATH,
        CANONICAL_REPORT_NAME,
        build_alarms,
        build_autonomous_report,
        build_phase_manifest,
        build_summary_html,
        collect_phase_metrics,
        evaluate_autonomous_report,
        load_blessed_baseline,
        resolve_evidence_pairs,
        write_artifact_pack,
    )
except ModuleNotFoundError:  # pragma: no cover - script execution path
    from _mujoco_grasp_fixture import (  # type: ignore[no-redef]
        GRASP_MJCF,
        MUJOCO_GRASP_CAMERAS,
        MUJOCO_GRASP_TASK,
        build_grasp_phases,
        build_grasp_protocol,
    )
    from _mujoco_grasp_wedge import (  # type: ignore[no-redef]
        BASELINE_REPORT_PATH,
        CANONICAL_REPORT_NAME,
        build_alarms,
        build_autonomous_report,
        build_phase_manifest,
        build_summary_html,
        collect_phase_metrics,
        evaluate_autonomous_report,
        load_blessed_baseline,
        resolve_evidence_pairs,
        write_artifact_pack,
    )


def generate_html_report(
    output_dir: Path,
    *,
    summary_html: str,
    evaluation_result: EvaluationResult,
) -> Path:
    """Generate the alarm-first HTML report for the MuJoCo grasp wedge."""
    from roboharness.reporting import generate_html_report as _generate

    return _generate(
        output_dir,
        MUJOCO_GRASP_TASK,
        title="Roboharness: MuJoCo Alarmed Grasp Loop",
        subtitle=(
            "One deterministic MuJoCo grasp run packaged for agent diagnosis: "
            "baseline drift, phase-local alarms, and the next checkpoint to inspect."
        ),
        accent_color="#1d6fd8",
        summary_html=summary_html,
        footer_text="Generated by <code>examples/mujoco_grasp.py --report</code>",
        meshcat_mode="iframe",
        evaluation_result=evaluation_result,
    )


def _describe_evidence_state(manifest, evidence_pairs) -> str:
    if manifest.failed_phase_id is None:
        return "PASS/no failed phase"
    if not evidence_pairs or all(pair.status == "empty" for pair in evidence_pairs):
        return "FAIL/empty evidence"
    statuses = {pair.status for pair in evidence_pairs}
    if "mismatch" in statuses:
        return "FAIL/manifest mismatch"
    if "ambiguous" in statuses:
        return "FAIL/ambiguous still-image evidence"
    if "partial" in statuses or "empty" in statuses:
        return "FAIL/partial evidence"
    return "FAIL/full evidence"


def main() -> None:
    parser = argparse.ArgumentParser(description="Roboharness MuJoCo alarmed grasp loop")
    parser.add_argument(
        "--output-dir",
        default="./harness_output",
        help="Output directory (default: ./harness_output)",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Generate the HTML report after writing the machine-readable artifact pack",
    )
    parser.add_argument("--width", type=int, default=640, help="Render width (default: 640)")
    parser.add_argument("--height", type=int, default=480, help="Render height (default: 480)")
    parser.add_argument(
        "--baseline-report",
        default=str(BASELINE_REPORT_PATH),
        help="Path to the blessed baseline autonomous_report.json fixture",
    )
    parser.add_argument(
        "--assert-success",
        action="store_true",
        help="Exit non-zero if the evaluator produces degraded or failing alarms",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)

    print("=" * 60)
    print("  Roboharness: MuJoCo Alarmed Grasp Loop")
    print("=" * 60)

    print("\n[1/5] Loading MuJoCo model (inline XML) ...")
    backend = MuJoCoMeshcatBackend(
        xml_string=GRASP_MJCF,
        cameras=MUJOCO_GRASP_CAMERAS,
        render_width=args.width,
        render_height=args.height,
    )
    print("      Model loaded. Actuators: 3 (z-slide, left-finger, right-finger)")

    meshcat_viz: MeshcatVisualizer | None = None
    if args.report:
        meshcat_viz = MeshcatVisualizer(
            backend._model,
            backend._data,
            width=args.width,
            height=args.height,
        )
        print("      Meshcat visualizer ready for 3D checkpoint exports.")

    print("[2/5] Setting up harness with canonical grasp phases ...")
    harness = Harness(backend, output_dir=str(output_dir), task_name=MUJOCO_GRASP_TASK)
    phases = build_grasp_phases()
    harness.load_protocol(build_grasp_protocol())
    print(f"      Protocol: {harness.active_protocol.name}")
    print(f"      Checkpoints: {harness.list_checkpoints()}")

    print("[3/5] Running deterministic grasp simulation ...")
    harness.reset()

    checkpoint_results: dict[str, object] = {}
    for phase_name, actions in phases.items():
        result = harness.run_to_next_checkpoint(actions)
        if result is None:
            raise RuntimeError(
                f"Expected checkpoint '{phase_name}', but the harness returned None."
            )

        checkpoint_results[phase_name] = result
        n_views = len(result.views)
        trial_phase_dir = output_dir / MUJOCO_GRASP_TASK / "trial_001" / phase_name
        print(
            f"      Checkpoint '{phase_name}': {n_views} views captured"
            f" | step={result.step} | sim_time={result.sim_time:.3f}s"
        )
        print(f"        -> {trial_phase_dir}")

        if meshcat_viz is not None:
            meshcat_viz.sync()
            scene_path = trial_phase_dir / "meshcat_scene.html"
            meshcat_viz.export_html(scene_path)
            print(f"        -> Meshcat 3D: {scene_path}")

    print("[4/5] Building alarmed artifact pack ...")
    trial_dir = output_dir / MUJOCO_GRASP_TASK / "trial_001"
    baseline_report_path = Path(args.baseline_report)
    baseline_visual_root = baseline_report_path.resolve().parent / "baseline_visual"
    baseline_report = load_blessed_baseline(baseline_report_path)
    snapshot_metrics = collect_phase_metrics(harness, backend, checkpoint_results)
    autonomous_report = build_autonomous_report(
        snapshot_metrics=snapshot_metrics,
        baseline_report=baseline_report,
        baseline_source=str(baseline_report_path),
    )
    report_path = trial_dir / "autonomous_report.json"
    evaluation_result = evaluate_autonomous_report(
        autonomous_report,
        report_path=str(report_path),
    )
    alarms = build_alarms(autonomous_report, evaluation_result)
    manifest = build_phase_manifest(autonomous_report, evaluation_result, alarms)

    evidence_pairs = []
    canonical_report_path = output_dir / CANONICAL_REPORT_NAME
    if args.report:
        evidence_pairs = resolve_evidence_pairs(
            trial_dir=trial_dir,
            baseline_visual_root=baseline_visual_root,
            manifest=manifest,
            report=autonomous_report,
        )
        html_report_path = generate_html_report(
            output_dir,
            summary_html=build_summary_html(
                autonomous_report,
                alarms,
                manifest,
                evidence_pairs,
            ),
            evaluation_result=evaluation_result,
        )
        shutil.copyfile(html_report_path, canonical_report_path)
        print(f"      HTML report: {canonical_report_path}")
    else:
        html_report_path = None

    write_artifact_pack(
        trial_dir=trial_dir,
        report=autonomous_report,
        evaluation_result=evaluation_result,
        alarms=alarms,
        manifest=manifest,
        report_generated=args.report,
    )

    print(f"      autonomous_report.json: {report_path}")
    print(f"      alarms.json: {trial_dir / 'alarms.json'}")
    print(f"      phase_manifest.json: {trial_dir / 'phase_manifest.json'}")

    print("[5/5] Summary")
    total_images = len(list(trial_dir.rglob("*_rgb.png"))) if trial_dir.exists() else 0
    selected_views = ", ".join(manifest.primary_views[:2]) if manifest.primary_views else "none"
    print(f"      {total_images} images saved to: {trial_dir}")
    verdict_line = (
        f"      Verdict: {evaluation_result.verdict.value.upper()}"
        f" | failed phase: {manifest.failed_phase or 'none'}"
        f" | selected views: {selected_views}"
    )
    if manifest.failed_phase_id is not None:
        verdict_line += f" | rerun hint: {manifest.rerun_hint}"
    print(verdict_line)
    if args.report:
        print(f"      Evidence status: {_describe_evidence_state(manifest, evidence_pairs)}")
    print(f"      Agent next action: {manifest.agent_next_action}")

    failures = [result.message for result in evaluation_result.failed]
    if failures:
        print("      Alarm details:")
        for message in failures:
            print(f"        FAIL: {message}")
    else:
        print("      No active alarms. Current run matches the blessed baseline envelope.")

    print("\n  Output structure:")
    if trial_dir.exists():
        for child in sorted(trial_dir.iterdir()):
            if child.is_dir():
                print(f"    {child.name}/")
                for file_name in sorted(f.name for f in child.iterdir() if f.is_file()):
                    print(f"      {file_name}")
            else:
                print(f"    {child.name}")
    if args.report and html_report_path is not None:
        print(f"    {CANONICAL_REPORT_NAME}")
        print(f"    {html_report_path.name}")

    print("\n" + "=" * 60)

    if args.assert_success and failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
